spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.ilevhyousrrcrzenwhst
spring.datasource.password=UFCSPA2026@

spring.flyway.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.flyway.user=postgres.ilevhyousrrcrzenwhst
spring.flyway.password=UFCSPA2026@
spring.flyway.baseline-on-migrate=false

DB_PASSWORD=UFCSPA2026@
JWT_SECRET=santa-rita-dashboard-secret-key-2026-muito-segura-aqui
