spring.application.name=santa-rita-dashboard-service
server.port=${PORT:9000}

spring.datasource.url=jdbc:postgresql://${PGHOST:aws-1-us-east-2.pooler.supabase.com}:${PGPORT:6543}/${PGDATABASE:postgres}?prepareThreshold=0
spring.datasource.username=${PGUSER:postgres.ilevhyousrrcrzenwhst}
spring.datasource.password=${PGPASSWORD:UFCSPA2026@}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:santa-rita-dashboard-secret-key-2026-muito-segura-aqui}
jwt.expiration=86400000

spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://${PGHOST:aws-1-us-east-2.pooler.supabase.com}:${PGPORT:6543}/${PGDATABASE:postgres}?prepareThreshold=0
spring.flyway.user=${PGUSER:postgres.ilevhyousrrcrzenwhst}
spring.flyway.password=${PGPASSWORD:UFCSPA2026@}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
